services:

  frontend_service_user:
    container_name: fe_service_user
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "5001:5173"
    environment:
      TZ: Europe/Berlin

