services:
  mongo-user:
    container_name: db_user
    image: mongo:latest
    volumes:
      - ./Database/mongodb_user:/data/db
    ports:
      - "35555:27017"
    command: mongod

  backend_service_user:
    container_name: be_service_user
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - mongo-user
    volumes:
      - ./:/app
    ports:
      - "4001:3000"
    environment:
      TZ: Europe/Berlin
