services:

  backend_service_user:
    container_name: be_service_user
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
      - ./index.js:/app/index.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4001:3000"
    environment:
      TZ: Europe/Berlin

  mongo-user:
    container_name: db_user
    image: mongo:latest
    volumes:
      - ./Database/mongodb_user:/data/db
    ports:
      - "35555:27017"
    command: mongod --quiet --logpath /dev/null
